-- CLIMA AUTO - estructura y políticas completas
create table if not exists public.administradores (
  usuario_id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  created_at timestamptz not null default now()
);
create table if not exists public.configuracion_negocio (
  id bigint generated by default as identity primary key,
  nombre_negocio text not null default 'Clima Auto', eslogan text, descripcion text,
  whatsapp text, telefono text, correo text, direccion text, horario text,
  google_maps_url text, facebook_url text, instagram_url text, tiktok_url text, youtube_url text,
  logo_url text, logo_ruta_storage text, portada_url text, portada_ruta_storage text, mensaje_whatsapp text, updated_at timestamptz default now()
);
create table if not exists public.servicios (
  id bigint generated by default as identity primary key,
  nombre text not null, descripcion text, imagen_url text, ruta_storage text, precio_desde numeric(12,2),
  mostrar_precio boolean not null default false, visible boolean not null default true,
  destacado boolean not null default false, orden integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.trabajos (
  id bigint generated by default as identity primary key,
  titulo text not null, vehiculo text, anio_vehiculo integer, problema text,
  trabajo_realizado text, resultado text, imagen_principal_url text, ruta_storage text, fecha_trabajo date,
  visible boolean not null default true, destacado boolean not null default false,
  orden integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.trabajo_imagenes (
  id bigint generated by default as identity primary key,
  trabajo_id bigint not null references public.trabajos(id) on delete cascade,
  imagen_url text not null, ruta_storage text, texto_alternativo text,
  orden integer not null default 0
);

-- Compatibilidad con instalaciones anteriores
alter table public.configuracion_negocio add column if not exists logo_ruta_storage text;
alter table public.configuracion_negocio add column if not exists portada_ruta_storage text;
alter table public.servicios add column if not exists ruta_storage text;
alter table public.trabajos add column if not exists ruta_storage text;

alter table public.administradores enable row level security;
alter table public.configuracion_negocio enable row level security;
alter table public.servicios enable row level security;
alter table public.trabajos enable row level security;
alter table public.trabajo_imagenes enable row level security;
-- Limpia políticas anteriores de este paquete
drop policy if exists "Admin lee su registro" on public.administradores;
create policy "Admin lee su registro" on public.administradores for select to authenticated using (usuario_id=auth.uid());
drop policy if exists "Configuracion publica" on public.configuracion_negocio;
create policy "Configuracion publica" on public.configuracion_negocio for select to anon,authenticated using (true);
drop policy if exists "Admin modifica configuracion" on public.configuracion_negocio;
create policy "Admin modifica configuracion" on public.configuracion_negocio for all to authenticated using (exists(select 1 from public.administradores a where a.usuario_id=auth.uid())) with check (exists(select 1 from public.administradores a where a.usuario_id=auth.uid()));
drop policy if exists "Servicios publicos" on public.servicios;
create policy "Servicios publicos" on public.servicios for select to anon,authenticated using (visible=true or exists(select 1 from public.administradores a where a.usuario_id=auth.uid()));
drop policy if exists "Admin modifica servicios" on public.servicios;
create policy "Admin modifica servicios" on public.servicios for all to authenticated using (exists(select 1 from public.administradores a where a.usuario_id=auth.uid())) with check (exists(select 1 from public.administradores a where a.usuario_id=auth.uid()));
drop policy if exists "Trabajos publicos" on public.trabajos;
create policy "Trabajos publicos" on public.trabajos for select to anon,authenticated using (visible=true or exists(select 1 from public.administradores a where a.usuario_id=auth.uid()));
drop policy if exists "Admin modifica trabajos" on public.trabajos;
create policy "Admin modifica trabajos" on public.trabajos for all to authenticated using (exists(select 1 from public.administradores a where a.usuario_id=auth.uid())) with check (exists(select 1 from public.administradores a where a.usuario_id=auth.uid()));
drop policy if exists "Imagenes trabajos publicas" on public.trabajo_imagenes;
create policy "Imagenes trabajos publicas" on public.trabajo_imagenes for select to anon,authenticated using (exists(select 1 from public.trabajos t where t.id=trabajo_id and (t.visible=true or exists(select 1 from public.administradores a where a.usuario_id=auth.uid()))));
drop policy if exists "Admin modifica imagenes" on public.trabajo_imagenes;
create policy "Admin modifica imagenes" on public.trabajo_imagenes for all to authenticated using (exists(select 1 from public.administradores a where a.usuario_id=auth.uid())) with check (exists(select 1 from public.administradores a where a.usuario_id=auth.uid()));
-- Después de crear un usuario en Authentication, reemplazá el UUID:
-- insert into public.administradores(usuario_id,nombre) values ('UUID_DEL_USUARIO','Administrador');


-- STORAGE PARA IMÁGENES DE SERVICIOS (bucket público existente SIS_AUTO)
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Agrega la referencia interna del archivo y permite al administrador
-- subir, reemplazar y eliminar imágenes del bucket público SIS_AUTO.

alter table public.servicios
add column if not exists ruta_storage text;

-- Lectura pública de imágenes (el bucket también debe estar marcado como público).
drop policy if exists "SIS_AUTO lectura publica" on storage.objects;
create policy "SIS_AUTO lectura publica"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'SIS_AUTO');

-- Solo usuarios registrados en public.administradores pueden subir imágenes.
drop policy if exists "SIS_AUTO admin inserta" on storage.objects;
create policy "SIS_AUTO admin inserta"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'SIS_AUTO'
  and exists (
    select 1 from public.administradores a
    where a.usuario_id = auth.uid()
  )
);

-- Se incluye update por compatibilidad futura, aunque esta versión usa nombres únicos.
drop policy if exists "SIS_AUTO admin actualiza" on storage.objects;
create policy "SIS_AUTO admin actualiza"
on storage.objects for update
to authenticated
using (
  bucket_id = 'SIS_AUTO'
  and exists (
    select 1 from public.administradores a
    where a.usuario_id = auth.uid()
  )
)
with check (
  bucket_id = 'SIS_AUTO'
  and exists (
    select 1 from public.administradores a
    where a.usuario_id = auth.uid()
  )
);

-- Solo administradores pueden borrar archivos del bucket.
drop policy if exists "SIS_AUTO admin elimina" on storage.objects;
create policy "SIS_AUTO admin elimina"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'SIS_AUTO'
  and exists (
    select 1 from public.administradores a
    where a.usuario_id = auth.uid()
  )
);
